### ISSUE TITLE
找到一个可以不被BE提示文件block的方法

### ISSUE THREAD

**Issue by wysnxzm** [mgsweet/PUBG-Macro-Assist#13]
会不会封号就不知道了,至少目前两个月没有问题
自动压枪还是有问题,如果蓝洞不出训练房间无限子弹还是很难测试出所有枪械的压枪频率和力度
垃圾蓝洞,退我98

**Comment by mgsweet** [comment]
新版本貌似枪械数据改了，但我已经把游戏删了....你们需要自己测试下
