### ISSUE TITLE
大佬能告诉我为什么能够检测鼠标是否可见吗。

### ISSUE THREAD

**Issue by ddduuuttt** [mgsweet/PUBG-Macro-Assist#15]
isMouseShown()			; Suspends the script when mouse is visible ie: inventory, menu, map.
	{            
                StructSize := A_PtrSize + 16//
		VarSetCapacity(InfoStruct, StructSize)//清空InfoStruct 16b空间
		NumPut(StructSize, InfoStruct)/将StructSize写入InfoStruct
		DllCall("GetCursorInfo", UInt, &InfoStruct)//获取当前鼠标句柄
		Result := NumGet(InfoStruct, 8)//返回句柄+8的值，
大佬能告诉我为什么能够检测鼠标是否可见吗。。。

**Comment by mgsweet** [comment]
这其实是参考别人的代码，个人解读下就是为 GetCursorInfo 这个 DllCall 的返回结构体`CURSORINFO `分配了一个空间，然后自己定义一个结构体去解释它，应该是解释的 flags 这个属性，结构体查看https://msdn.microsoft.com/en-us/library/ms648381

**Comment by wysnxzm** [comment]
@mgsweet 减少移动间隔可以更好模拟手动操作(不会出现一跳跳的感觉)
但是有一个问题没法解决 +1补偿值的时候,很容易压过头
