### ISSUE TITLE
AHK是个好东西

### ISSUE THREAD

**Issue by wysnxzm** [mgsweet/PUBG-Macro-Assist#4]
AHK其实用的人越少越好,哪些被封禁的用户在我看来只有两个理由:
第一,使用过于老旧的AHK编译版本(我曾经被坑过)AHK在多年前是十分火爆的"作弊工具",但是到了现在,用的人寥寥无几自然没有关注和对应新版本的特征检测手段
第二:使用了其他修改游戏数据的外挂,开挂这种东西,只有一次和无数次,常在河边走哪能不湿鞋

**Comment by mgsweet** [comment]
@wysnxzm 刚开始只是学着写了个大跳的，然后....越陷越深

**Comment by jishankai** [comment]
@wysnxzm 先买游戏再来发表观点。你看来的两个理由都是想当然

**Comment by wysnxzm** [comment]
@mgsweet 到最后发现游戏的乐趣还是在于被虐

**Comment by myloft** [comment]
@wysnxzm BE是通过检测脚本关键字进行封禁的,带补偿的版本触发了关键词AutoFire NoRecoil而且官方似乎特别关注了这个脚本，在最新的关键词里加入了Compensation:=0,ToolTip.

**Comment by myloft** [comment]
理论上讲把关键词替换成AAA BBB之类是可以正常使用的(不承担责任)，或者自行编译一个不叫Autohotkey的版本。

**Comment by wysnxzm** [comment]
@myloft Autohotkey.exe的进程名是可以自定义的,你说的关键词是脚本内容触发?BE怎么可能扫描的到编译后的代码?不过如果被特别关注了,那就可以说是GG了

**Comment by myloft** [comment]
@wysnxzm 即使自己编译的程序，内存中依旧是存在源代码，你可以用process explore查看，更不用说BE了，这是我随手编译的。
![dump](https://user-images.githubusercontent.com/25258169/33238094-9de8409e-d2c0-11e7-9218-7ddb01d79d08.PNG)
至于BE的关键词你可以把BE dump下来，看起来目前只检名为Autohotkey.exe的程序，没有对其它进程名进行检测
