### ISSUE TITLE
关于封号的简单探讨。

### ISSUE THREAD

**Issue by sadnecc** [mgsweet/PUBG-Macro-Assist#5]
1.首先单纯的AHK是不可能封号的，
2.做成EXE的话有一定几率被特征码封,每个人下去自己加VM壳子的话不知道会不会好点，
3.FPS类游戏整个来说，主要就是压枪，单击鼠标 ,两块儿内容 ，鼠标X轴的移动还是人手,Y轴交给代码处理。这里边问题就是Y轴向下移动的幅度 , 移动的时间间距，以及人手压枪X轴会带来少许的变化 , 假设说 每次 Y轴向下移动2个单位 , X轴可能在Y轴每一次下压都有少许的变化，每一次变化都有随机值，包括X Y 轴下压的幅度， 都不应该是一成不变的，现在的AHK貌似都是一次下压两个像素，以两个像素作为单位说实话，有点高。不够精确，如果能精确一些，应该会好很多， 比如这次下压1.9下次下压 2.2 这样的。足够随机,拟人。

**Comment by mgsweet** [comment]
@sadnecc 你提醒了我再研究了下DLL指令，其接受的是一个Dword（32位），虽然貌似可以接受一个浮点类型，但不知道所谓的`绝对数据作为鼠标的实际X坐标`是否能接受一个浮点值，这个有待进一步研究。

**Comment by sxzxs** [comment]
我知道的是剑灵这个游戏，如果是转成.exe的话不太可能封号，如果是.ahk的话会封号

**Comment by tinxy1989** [comment]
我之前用ahk 被封了。 
感觉连点如果 leftclick sleep数值过低的话 ,很容易被瞬间踢出服务器封号。 
然后压枪我现在用的是私人编写的，y轴也用了随机值，目前玩了十来把 还没被封号。

**Comment by sxzxs** [comment]
是的，我也发现这个问题了
