### ISSUE TITLE
新的机制按住右键之后 补偿一直默认成1

### ISSUE THREAD

**Issue by emoxing885** [mgsweet/PUBG-Macro-Assist#8]
旧的补偿方式用着没问题 但是新的那个办法按住右键 补偿值就恢复成1 不知道是什么原因。 我用的是razer 没有设置什么特殊的按键

**Comment by mgsweet** [comment]
新的还有点bug未修复可能，因为我debug中途被ban了哈哈，你需要尝试修复一下，或者可以版本回退，回退到上一个版本。

**Comment by mgsweet** [comment]
回退到 `commit 22cb3048248a74c19c0af2a28270d0c681fb8791` 这个1.2版本
